services:
  alertmanager:
    image: prom/alertmanager
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.test`)"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
    restart: "no"
    networks:
      - devops-net
networks:
  devops-net:
    external: true
