
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-lab
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.test`)"
      - "traefik.http.routers.jenkins.entrypoints=web"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
    restart: "no"
    networks:
      - devops-net

volumes:
  jenkins_data:

networks:
  devops-net:
    external: true