services:
  nexus:
    image: sonatype/nexus3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nexus.rule=Host(`nexus.test`)"
      - "traefik.http.services.nexus.loadbalancer.server.port=8081"
    restart: "no"
    networks:
      - devops-net

networks:
  devops-net:
    external: true
