services:
  vault:
    image: hashicorp/vault
    command: server -dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.test`)"
      - "traefik.http.services.vault.loadbalancer.server.port=8200"
    restart: "no"
    networks:
      - devops-net
networks:
  devops-net:
    external: true
