services:
  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.test`)"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    restart: "no"
    networks:
      - devops-net
networks:
  devops-net:
    external: true
